### ISSUE TITLE
Cats-effect 3

### ISSUE THREAD

**Issue by domaspoliakas** [ChristopherDavenport/vault#159]
Greetings. 

Are there any plans for a ce3 version of this? If not, would you accept a PR?

**Comment by rossabaker** [comment]
We'll need a Unique as well.

**Comment by rossabaker** [comment]
Oh, unique is in progress: https://github.com/ChristopherDavenport/unique/pull/140

**Comment by domaspoliakas** [comment]
I'll work on this now, so hopefully there'll be a PR later.

**Comment by yanns** [comment]
Seems to be in progress in https://github.com/ChristopherDavenport/vault/pull/175

**Comment by domaspoliakas** [comment]
Is now merged
